=== ancara22/Data-Recording-Rig/Resources/Data_Format_0.6/Schema_0.6/device_schema_0.6.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "RIG Device/0.6",
    "title": "Hardware details of RIG",
    "description": "Device details of RIG",
    "type": "object",
    "properties": {
        "name":{
            "description": "The name of the device",
            "type": "string"
        },
        "description": {
            "description": "Description of device.",
            "type": "string"
        },
        "version": {
            "description": "Version of device.",
            "type": "number"
        },
        "hardware": {
            "description": "Hardware associated with device.",
            "type": "object",
            "properties": {
                "gsr": {
                    "description": "Description of hardware used to record GSR data.",
                    "type": "object",
                    "properties": {
                        "manufacturer": {
                            "description": "Manufacturer of GSR device.",
                            "type": "string"
                        },
                        "model": {
                            "description": "Model of the GSR device.",
                            "type": "string"
                        }
                    }
                },
                "eeg": {
                    "description": "Description of hardware used to record EEG data.",
                    "type": "object",
                    "properties": {
                        "manufacturer": {
                            "description": "Manufacturer of EEG device.",
                            "type": "string"
                        },
                        "model": {
                            "description": "Model of the EEG device.",
                            "type": "string"
                        },
                        "sensors": {
                            "description": "Sensors of the device",
                            "type": "object",
                            "patternProperties": {
                                "^[a-zA-Z0-9_.-]*$": {
                                    "type": "string",
                                    "description": "Location and type of sensor" 
                                }
                            },
                            "additionalProperties": false
                        }
                    },
                    "required": ["manufacturer", "model", "sensors"],
                    "additionalProperties": false
                },
                "camera": {
                    "description": "Camera on device.",
                    "type": "object",
                    "properties": {
                        "manufacturer": {
                            "description": "Manufacturer of camera.",
                            "type": "string"
                        },
                        "model": {
                            "description": "Model of camera.",
                            "type": "string"
                        }
                    }
                },
                "microphone": {
                    "description": "Microphone on device.",
                    "type": "object",
                    "properties": {
                        "manufacturer": {
                            "description": "Manufacturer of microphone.",
                            "type": "string"
                        },
                        "model": {
                            "description": "Model of microphone.",
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "required": ["name", "description", "version", "hardware"]
}

=== ancara22/Data-Recording-Rig/Resources/Data_Format_0.6/Converter/output/device_sample_0.6.json
{"$schema":"../../Data Format_0.6/Schema_0.6/device_schema_0.6.json","name":"RIG","description":"RIG hardware.","version":0.3,"hardware":{"gsr":{"manufacturer":"Rasberry Pi","model":"Grove GSR sensor (https://thepihut.com/products/grove-gsr-sensor)."},"eeg":{"manufacturer":"Emotiv. See https://emotiv.gitbook.io/cortex-api/ for documentation.","model":"Epoc X","sensors":{"AF3":"AF3 description","F7":"F7 description","F3":"F3 description","FC5":"FC5 description","T7":"T7 description","P7":"P7 description","O1":"O1 description","O2":"O2 description","P8":"P8 description","T8":"T8 description","FC6":"FC6 description","F4":"F4 description","F8":"F8 description","AF4":"AF4 description"}},"microphone":{"manufacturer":"Rasberry Pi","model":"USB microphone"},"camera":{"manufacturer":"Rasberry Pi","model":"ZeroCam"}}}
